"""empty message

Revision ID: deb7194c7eb3
Revises: e3b4c7907d91
Create Date: 2024-04-12 13:27:39.789054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'deb7194c7eb3'
down_revision: Union[str, None] = 'e3b4c7907d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prodcut_per_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_per_request')
    op.add_column('request', sa.Column('products', sa.Integer(), nullable=False))
    op.add_column('request', sa.Column('data', sa.TIMESTAMP(), nullable=False))
    op.drop_column('request', 'date')
    op.drop_column('request', 'products_per_request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('products_per_request_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('request', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('request', 'data')
    op.drop_column('request', 'products')
    op.create_table('product_per_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number_request', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['number_request'], ['request.id'], name='product_per_request_number_request_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_per_request_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_per_request_pkey')
    )
    op.drop_table('prodcut_per_request')
    # ### end Alembic commands ###
