"""empty message

Revision ID: e3b4c7907d91
Revises: b3e1093959fd
Create Date: 2024-04-12 13:06:04.949874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3b4c7907d91'
down_revision: Union[str, None] = 'b3e1093959fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('products_per_request_id', sa.Integer(), nullable=False))
    op.drop_column('request', 'products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('products', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('request', 'products_per_request_id')
    # ### end Alembic commands ###
